baseURL = "/"
languageCode = "en-us"
title = "pureudon 網頁設計公司"
themesDir = "themes"
theme = "hugo-serif-theme"


[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-mobile.svg"
    mobile_height = "36px"
    desktop = "images/logo/logo.svg"
    desktop_height = "36px"
    alt = "Serif - A Hugo Business Theme"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = '© 2021 <a href="https://pureudon.com">pureudon.com</a> All Rights Reserved'

[menu]
  # Main Menu
  [[menu.main]]
    name = "首頁"
    url = "/"
      weight = 1

  [[menu.main]]
      name = "公司電郵方案"
      url = "/services/company_email_solution/"
      weight = 4

  [[menu.main]]
      name = "網上商店"
      url = "/services/e-shop/"
      weight = 4

  [[menu.main]]
      name = "線上系統開發"
      url = "/services/web-development/"
      weight = 4

  [[menu.main]]
      name = "服務簡介"
      url = "/service_table/"
      weight = 4

  [[menu.main]]
      name = "聯絡我們"
      url = "/contact/"
      weight = 7

  # Footer Menu
 [[menu.footer]]
    name = "首頁"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "聯絡我們"
    url = "/contact/"
      weight = 2
